version: 2.1

jobs:
  build:
    working_directory: ~/circleci-js
    docker:
      - image: "circleci/node:14"
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    working_directory: ~/circleci-js
    docker:
      - image: "circleci/node:14"
    steps:
      - checkout
      - run: cd web && npm install
      - run: cd web && npm run lint
      - run: cd web && npm run build
      - run: cd web && npm run test:coverage

workflows:
 version: 2
  concurrently:
    jobs:
      - cloud-functions
      - web
